# Mudasir Sohail
# Assignment 8
# Course : DS

In [2]:
import numpy as np

# 47. Create an array of 10 zeros
zeros_array = np.zeros(10)
print("Array of 10 zeros:\n", zeros_array)

Array of 10 zeros:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
# 48. Create an array of 5 ones, multiply by 10
ones_array = np.ones(5) * 10
print("\nArray of 5 ones multiplied by 10:\n", ones_array)



Array of 5 ones multiplied by 10:
 [10. 10. 10. 10. 10.]


In [6]:

# 49. Create array from 0 to 50 (inclusive) with step 5
step_array = np.arange(0, 51, 5)
print("\nArray from 0 to 50 with step 5:\n", step_array)


Array from 0 to 50 with step 5:
 [ 0  5 10 15 20 25 30 35 40 45 50]


In [7]:
# 50. Create array of 100 random integers (1 to 100), find min and max
random_array = np.random.randint(1, 101, 100)
print("\nRandom integers array:\n", random_array)
print("Minimum value:", random_array.min())
print("Maximum value:", random_array.max())



Random integers array:
 [ 76  77  68  76  53  53  13  35  99  60  14 100  12  68  65  26  49  34
   1  54  94  55   7  22  27  94   2   9  66  76  94  80  80  29  48  91
  97  37  61  91  37  53  72  37  75  54  55  23  98   4  94  81  67  52
  56  47  75  16   5  15   2  95  46  52  93  44  72  22  77  47  96  24
  95  34  59  91  34  55  25  44   1  25  27  17  61  54  55  46  63  98
  22  48  16  19  53  68   2  21  26  92]
Minimum value: 1
Maximum value: 100


In [8]:
# 51. Element-wise addition and multiplication between two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print("\nElement-wise addition:", arr1 + arr2)
print("Element-wise multiplication:", arr1 * arr2)



Element-wise addition: [5 7 9]
Element-wise multiplication: [ 4 10 18]


In [9]:

# 52. Create 2D array (3x3) of random numbers and calculate mean
array_2d = np.random.rand(3, 3)
print("\n2D Random Array:\n", array_2d)
print("Mean of array:", array_2d.mean())



2D Random Array:
 [[0.09000351 0.92956107 0.90281132]
 [0.60262983 0.54168863 0.64305652]
 [0.69518903 0.14964015 0.15044458]]
Mean of array: 0.5227805154955217


In [10]:
# 53. Create array and reshape from (4, 5) to (5, 4)
reshaped_array = np.arange(20).reshape(4, 5)
print("\nOriginal (4x5) Array:\n", reshaped_array)
reshaped_array = reshaped_array.reshape(5, 4)
print("Reshaped (5x4) Array:\n", reshaped_array)


Original (4x5) Array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Reshaped (5x4) Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [11]:
# 54. Find index of maximum value in array
arr = np.array([1, 7, 3, 9, 5])
max_index = np.argmax(arr)
print("\nArray:", arr)
print("Index of maximum value:", max_index)


Array: [1 7 3 9 5]
Index of maximum value: 3


In [12]:
import pandas as pd

# 55. Create DataFrame from a dictionary
data = {
    "Name": ["Ali", "Sara", "Ahmed"],
    "Age": [20, 22, 19],
    "Score": [88, 95, 76]
}
df = pd.DataFrame(data)
print("\nDataFrame:\n", df)



DataFrame:
     Name  Age  Score
0    Ali   20     88
1   Sara   22     95
2  Ahmed   19     76


In [13]:
# 56. Select "Name" column
print("\nName column:\n", df["Name"])


Name column:
 0      Ali
1     Sara
2    Ahmed
Name: Name, dtype: object


In [14]:
# 57. Add new column "Grade" based on Score
def grade(score):
    if score >= 90:
        return "A"
    elif score >= 80:
        return "B"
    elif score >= 70:
        return "C"
    else:
        return "D"

df["Grade"] = df["Score"].apply(grade)
print("\nDataFrame with Grade column:\n", df)


DataFrame with Grade column:
     Name  Age  Score Grade
0    Ali   20     88     B
1   Sara   22     95     A
2  Ahmed   19     76     C


In [15]:
# 58. Filter students with score > 85
high_scores = df[df["Score"] > 85]
print("\nStudents with score > 85:\n", high_scores)



Students with score > 85:
    Name  Age  Score Grade
0   Ali   20     88     B
1  Sara   22     95     A


In [16]:
# 59. Find mean and median of Score column
print("\nMean of Scores:", df["Score"].mean())
print("Median of Scores:", df["Score"].median())


Mean of Scores: 86.33333333333333
Median of Scores: 88.0


In [17]:
students_df = pd.read_csv("book1.csv")
print("\nFirst 5 rows of students.csv:\n", students_df.head())


First 5 rows of students.csv:
        Name  Age  Score
0     Hamza   20     92
1       Ali   22     85
2     Ahmed   19     78
3   Mudasir   25     90
4  Mussawir   20     88
